### ISSUE TITLE
Polyline breaks (issue with chunking?)

### ISSUE THREAD

**Issue by tomislav** [StephanGeorg/staticmaps#10]
I'm getting breaks in my polylines (top right corner below the marker).

![static-5](https://user-images.githubusercontent.com/656/42810638-aedd237e-89b8-11e8-94a8-a55a8c953bcc.png)

This is 137 points. Since chunking is done at every 120 points I believe it is causing this because the last point of the previous chunked line is not also set as the first point of the next chunked line, causing gaps when being drawn.

**Comment by StephanGeorg** [comment]
Hi @tomislav 

![06-polyline](https://user-images.githubusercontent.com/7861660/42868830-a0b98cc2-8a73-11e8-9793-829c182a01e0.jpg)

Sorry, but I cannot reproduce the issue. The above example is made with 11,231 waypoints. Would you please share the route geometry in a gist or something?

**Comment by tomislav** [comment]
I think it's because you have so many points that the gaps are not visible at that zoom level.

Here is the poly line geometry from my example: https://gist.github.com/tomislav/37b081e9bab8dfc935047246b1c23c62

Excerpt from my code:

```
options = {
  width: 1200,
  height: 630,
  imageMagick: true,
  tileUrl: "https://cartodb-basemaps-a.global.ssl.fastly.net/rastertiles/voyager_labels_under/{z}/{x}/{y}@2x.png",
  tileSize: 512,
  paddingX: 60,
  paddingY: 60
};

map = new StaticMaps(options);

line = {
  coords: coords,
  color: '#4099ff',
  width: 12
};
map.addLine(line);

marker = {
  img: __dirname + '/public/images/puck-base@2x.png',
  offsetX: 0,
  offsetY: 18,
  width: 46,
  height: 46,
  coord: coords[coords.length - 1]
};
map.addMarker(marker);

map.render().then(function() {
  map.image.buffer();
}).then(function(buffer) {
  res.setHeader('Content-type', 'image/png');
  res.setHeader('Content-Length', buffer.length);
  res.status(200).send(buffer);
}).catch(function(err) {
  res.status(500).end();
});
```

**Comment by StephanGeorg** [comment]
Yes, you were totally right. Chunking the polylines array wasn't enough: https://github.com/StephanGeorg/staticmaps/blob/master/src/lib/staticmaps.js#L241

Thanks for helping. 
Fixed, tested and published.
