### ISSUE TITLE
Module not found: Error: Can't resolve 'child_process'  ...

### ISSUE THREAD

**Issue by roy1018** [StephanGeorg/staticmaps#11]
Excuse me, I have some problem.

When I "import StaticMaps from 'staticmaps" , there was some errors.
Module not found: Error: Can't resolve 'child_process' in ..
Module not found: Error: Can't resolve 'fs' in ..
Module not found: Error: Can't resolve 'net' in...
Module not found: Error: Can't resolve 'net' in..
Module not found: Error: Can't resolve 'tls'...

How do I solve it ? thanks.

**Comment by StephanGeorg** [comment]
Hi @roy1018.

- What node version do you use?
- Did you run npm test?
- fs, netm tls are node core modules. Do you use webpack?

**Comment by efendiev** [comment]
same issue with ionic
node v: 8.11.1

**Comment by StephanGeorg** [comment]
Sorry, I don‘t know Ionic. 

Staticmaps is built for server only. You cannot Import it into your browser application.

**Comment by efendiev** [comment]
ah thanks

**Comment by marcofdz** [comment]
Hi @StephanGeorg  Could you help me I have an error with fs, net, and tls. I working with webpack, angular and cypress

**Comment by StephanGeorg** [comment]
As I said before: staticmaps is built for node only to run in server environments not in browsers.
