### ISSUE TITLE
"Sharp.jpg is not a function" on .buffer('image/jpeg')

### ISSUE THREAD

**Issue by tberriot** [StephanGeorg/staticmaps#17]
Hi

it's seems there is a little bug on 'image.js' file when buffering jpeg.

```
 case 8:
     _context5.next = 10;
     return (0, _sharp2.default)(_this4.image).jpg(outputOptions).toBuffer();
```

.jpg not exist is sharp, but .jpeg

.jpeg is correctly used on save to file method

Regards
Thomas

**Comment by StephanGeorg** [comment]
Thanks @tberriot.

Fixed and published to npm.
