### ISSUE TITLE
Crash when adding polylines

### ISSUE THREAD

**Issue by foolishsailor** [StephanGeorg/staticmaps#18]
Error when adding polyline when using the below data set.

Environment:
Local Machine - Windows 10
Node 8.4

Error:
(sharp:45084): GLib-GObject-WARNING **: value "0" of type 'gint' is invalid or out of range for property 'width' of type 'gint'

(sharp:45084): GLib-GObject-WARNING **: value "0" of type 'gint' is invalid or out of range for property 'width' of type 'gint'
(node:45084) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: extract_area: parameter width not set

(node:45084) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:45084) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: extract_area: parameter width not set

Data Set
[
  [ -6.112413333, 53.3186994 ],
  [ -6.112244714, 53.318801543 ],
  [ -6.112018853, 53.319013417 ],
  [ -6.111948464, 53.319217244 ],
  [ -6.111722236, 53.319396249 ],
  [ -6.111270733, 53.319475927 ],
  [ -6.110888256, 53.319608853 ],
  [ -6.110752767, 53.3197874 ],
  [ -6.110902856, 53.319079141 ],
  [ -6.110596667, 53.31927947 ],
  [ -6.110298053, 53.319360898 ],
  [ -6.110421193, 53.319150348 ],
  [ -6.110704467, 53.319069725 ],
  [ -6.111708567, 53.3187084 ],
  [ -6.111935902, 53.318635819 ],
  [ -6.112124415, 53.318581099 ],
  [ -6.112284527, 53.318565893 ],
  [ -6.116562264, 53.317836425 ],
  [ -6.123460715, 53.320110469 ],
  [ -6.123576604, 53.320342053 ],
  [ -6.123683807, 53.320585651 ],
  [ -6.123834911, 53.320820915 ],
  [ -6.123995902, 53.321043142 ],
  [ -6.124164902, 53.321253164 ],
  [ -6.124335899, 53.321473887 ],
  [ -6.124521314, 53.321692692 ],
  [ -6.124702740, 53.321914654 ]
 ];

**Comment by StephanGeorg** [comment]
I updated sharp and this is what it looked like:

![06-polyline](https://user-images.githubusercontent.com/7861660/48844893-6715dd00-ed9b-11e8-9e5a-9b470491c431.jpg)

Would you please update staticmaps to latest and test again?

**Comment by foolishsailor** [comment]
Can confirm this works as well - however it fails when there is padding added
