### ISSUE TITLE
Error when using bounds

### ISSUE THREAD

**Issue by foolishsailor** [StephanGeorg/staticmaps#19]

**Comment by StephanGeorg** [comment]
What kind of error?

**Comment by foolishsailor** [comment]
The following code is causing the below error:

map.render( [ -6.1359285, 53.3145145, -6.1058408, 53.3253966 ]).then();

When using the other boudns sets - which are all very close geographically there is no problem


error:
(sharp:52064): GLib-GObject-WARNING **: value "0" of type 'gint' is invalid or out of range for property 'height' of type 'gint'

(sharp:52064): GLib-GObject-WARNING **: value "0" of type 'gint' is invalid or out of range for property 'height' of type 'gint'
(node:52064) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: extract_area: parameter height not set

(node:52064) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:52064) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: extract_area: parameter height not set


(sharp:52064): GLib-GObject-WARNING **: value "0" of type 'gint' is invalid or out of range for property 'height' of type 'gint'
(node:52064) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: extract_area: parameter height not set

**Comment by foolishsailor** [comment]
Actual code:
`map.render(bounds).then(() => {

       resolve('data:image/jpeg;base64,'+ map.image.image.toString('base64'));

      }).catch(function(err) {
         reject('******* Map Render Error *******',err);
      });`

Some additional bounds that work no problem...

 [ -6.1330751, 53.3136071, -6.1142106, 53.3284581 ]
 [ -6.1014215, 53.1375996, -6.1013698, 53.1377391 ]
 [ -6.1013955, 53.1376875, -6.1013818, 53.1377213 ]
 [ -6.1014311, 53.1376373, -6.1014008, 53.1377471 ]

**Comment by StephanGeorg** [comment]
I updated sharp and this is what it looked like:

![03-bbox](https://user-images.githubusercontent.com/7861660/48845142-0cc94c00-ed9c-11e8-8761-486ce4c4f177.png)

Please update staticmaps to latest and test again.

**Comment by foolishsailor** [comment]
I reinstalled staticmaps - there is only one version on NPM - 1.0.4

still getting same error:

using bounds [ -6.1359285, 53.3145145, -6.1058408, 53.3253966 ]


(sharp:8824): GLib-GObject-WARNING **: value "0" of type 'gint' is invalid or out of range for property 'height' of type 'gint'
(node:8824) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: extract_area: parameter height not set

(node:8824) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

(sharp:8824): GLib-GObject-WARNING **: value "0" of type 'gint' is invalid or out of range for property 'height' of type 'gint'

(node:8824) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: extract_area: parameter height not set

(sharp:8824): GLib-GObject-WARNING **: value "0" of type 'gint' is invalid or out of range for property 'height' of type 'gint'
(node:8824) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: extract_area: parameter height not set

**Comment by foolishsailor** [comment]
Thanks for getting to this so quickly!!!

Have narrowed down the problem:

I have the following options set

`
const options = {
width: 600,
height: 300,
quality: 80,
paddingY: 50,
paddingX:50,
tileUrl: 'https://api.mapbox.com/styles/v1/foolishsailor/cjdbkbbftbujk2smdohtu72m5/tiles/256/{z}/{x}/{y}?access_token=xxxxxxx',
tileSize: 256
};

`

When I remove the padding it works correctly
