### ISSUE TITLE
Error if render map with polyline

### ISSUE THREAD

**Issue by Longnt1208** [StephanGeorg/staticmaps#2]
Hi Stephan,

I have error when render map with polyline, this is my code 

`const polyline_test = {
    coords: [
      [13.399259,52.482659],
      [13.387849,52.477144],
      [13.40538,52.510632]
    ],
    color: '#0000FFBB',
    width: 3
  };

map.addLine(polyline_test);

map.render()
  .then(() => map.image.save('test_line.png'))  
  .then(() => console.log('File saved!'))
  .catch(function(err) { console.log(err); });`

and this is error message:

`src must be a string or a Buffer

(node:1997) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): null

(node:1997) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

rendering map with markers is ok.

**Comment by StephanGeorg** [comment]
Where did you initialize the map?

Try

```
const options = {
        width: 600,
        height: 200,
      };
const map = new StaticMaps(options);
const polyline_test = {
coords: [
[13.399259,52.482659],
[13.387849,52.477144],
[13.40538,52.510632]
],
color: '#0000FFBB',
width: 3
};
map.addLine(polyline_test);
map.render([13.437524, 52.4945528], 13)
  .then(() => map.image.save('test/out/01-center.jpg'))
  .then(() => {console.log('done!');})
  .catch(console.log);
```

**Comment by Longnt1208** [comment]
this is my full code:

`const StaticMaps = require('staticmaps');

const options = {
  width: 600,
  height: 400
};
const map = new StaticMaps(options);

const polyline_test = {
    coords: [
      [13.399259,52.482659],
      [13.387849,52.477144],
      [13.40538,52.510632]
    ],
    color: '#0000FFBB',
    width: 3
  };

map.addLine(polyline_test);

map.render()
  .then(() => map.image.save('test_line.png'))  
  .then(() => console.log('File saved!'))
  .catch(function(err) { console.log(err); });`

I think center and zoom is optional parameters ?

**Comment by StephanGeorg** [comment]
I'm sorry, but I cannot reproduce the error. I tested your code w/ node 4.4.3 and 8.6.0 and both got the correct output.

- Do you have gm installed?
- What is your node.js version?

> I think center and zoom is optional parameters ?

Yes, they are.

**Comment by Longnt1208** [comment]
I tested on another computer and it's ok, I think problem from my computer and relative with GM library. Thanks for very quick support.

**Comment by lokus1980** [comment]
I've just installed this package on my Mac and experiencing the same issue, but only when I want to draw a polyline or a polygon. Rendering a map alone works fine.

```
src must be a string or a Buffer
(node:33984) UnhandledPromiseRejectionWarning: null
(node:33984) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwinginside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:33984) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

My Node.js version is 8.10.0. Please help...

**Comment by StephanGeorg** [comment]
Hi.

Is GraphicsMagic installed and can you run gm in the terminal ?

Would you please clone the repo and npm test?

**Comment by lokus1980** [comment]
Hi Stephan,

GraphicsMagic is installed but gm seems to be an unknown command in the terminal.

Anyway, this is the result of npm test:

```
> staticmaps@0.7.6 test /Users/lukasz/Documents/Projects/staticmaps
> mocha --require babel-core/register



  StaticMap
    Initializing ...
      ✓ without any arguments
    Rendering ...
      ✓ render w/ center (1241ms)
      ✓ render w/ center from custom (856ms)
      1) render w/ bbox
      ✓ render w/ icon (1143ms)
      ✓ render w/out center (3620ms)
    Rendering w/ lines ...
src must be a string or a Buffer
(node:42341) UnhandledPromiseRejectionWarning: null
(node:42341) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:42341) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Looks like there's only problem with rendering lines...

**Comment by StephanGeorg** [comment]
Seems to be a gm error. Maps without polylines/polygons are rendered without gm, that’s why the first Tests passes. Try to fix the issue with your installed gm. The lib uses a node wrapper for the gm (node-gm) command. So if you’re not able to run gm in the terminal, it won‘t work. Try installing it via brew or install imagemagick and use imageMagick: true option.

**Comment by lokus1980** [comment]
True. I didn't know that imagemagick is a desktop app, not a stand-alone npm package so I can easily incorporate the whole thing into my web app being deployed on Heroku. If something needs a desktop app then Heroku needs a specially cooked buildpack which are not very reliable from my experience when trying to make PhantomJS work this way. So I'll use Google Maps Static API this time. Thanks for your help and time Stephan!
