### ISSUE TITLE
Error when using padding with polyline or bounds and certain data sets

### ISSUE THREAD

**Issue by foolishsailor** [StephanGeorg/staticmaps#20]
I have the following options set

const options = { width: 600, height: 300, quality: 80, paddingY: 50, paddingX:50, tileUrl: 'https://api.mapbox.com/styles/v1/foolishsailor/cjdbkbbftbujk2smdohtu72m5/tiles/256/{z}/{x}/{y}?access_token=xxxxxxx', tileSize: 256 };

map.render( [ -6.1359285, 53.3145145, -6.1058408, 53.3253966 ]).then();

error:
(sharp:52064): GLib-GObject-WARNING **: value "0" of type 'gint' is invalid or out of range for property 'height' of type 'gint'

(sharp:52064): GLib-GObject-WARNING **: value "0" of type 'gint' is invalid or out of range for property 'height' of type 'gint'
(node:52064) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: extract_area: parameter height not set

(node:52064) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:52064) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: extract_area: parameter height not set

(sharp:52064): GLib-GObject-WARNING **: value "0" of type 'gint' is invalid or out of range for property 'height' of type 'gint'
(node:52064) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: extract_area: parameter height not set

**Comment by StephanGeorg** [comment]
Ok, i think i know the problem. Give me a second...

**Comment by StephanGeorg** [comment]
Fixed and published to npm in staticmaps@1.0.5. Thanks @foolishsailor for debugging.

**Comment by foolishsailor** [comment]
Brilliant plugin that does some very sophisticated work and abstracts to an uber-simple interface that does EXACTLY what I need.  There is nothing else I have found that does this and i dont ahve the time to develop this.

Thanks for this and for your fast response!
