### ISSUE TITLE
Update dependency axios

### ISSUE THREAD

**Issue by cschwaderer** [StephanGeorg/staticmaps#26]
Staticmaps depends on axios, setting version `^0.17.1` in its package.json. However, axios is vulnerable to DoS attacks until version 0.18. So, you might want to update staticmaps' package.json to resolve version 0.18.1 or 0.19 of axios
See here: [https://www.npmjs.com/advisories/880](https://www.npmjs.com/advisories/880)

**Comment by StephanGeorg** [comment]
Cannot find any peer dependency.

**Comment by cschwaderer** [comment]
Sorry, had mixed up staticmaps and staticmap and thus posted on wrong repo, my bad.
