### ISSUE TITLE
Support for Node 13 and Sharp 0.23.2?

### ISSUE THREAD

**Issue by rapomon** [StephanGeorg/staticmaps#33]
Is there a future version that supports the latest versions of Node and Sharp?

Thanks.

**Comment by StephanGeorg** [comment]
Yes! https://github.com/StephanGeorg/staticmaps/commit/146d266224c57bfcacc70da802646a1c27766671

**Comment by StephanGeorg** [comment]
You can always compile your dependencies as described here: https://sharp.pixelplumbing.com/en/stable/install/

**Comment by rapomon** [comment]
Ok, thank you so much!
