### ISSUE TITLE
Promise from render function never called

### ISSUE THREAD

**Issue by JulienSmartEasHome** [StephanGeorg/staticmaps#52]
Hello all !

I tried from yesterday to implement staticMaps with default examples, without success.

map.render(center, zoom)
  .then(() => map.image.save('center.png'))  
  .then(() => console.log('File saved!'))
  .catch(function(err) { console.log(err); });

I have no error catched, et pormise for save image is not called.

Version of node is v10.23.0 and sharp is 0.27.1

Can you help me please ?

Thnaks you very much
Julien

**Comment by StephanGeorg** [comment]
Could you please clone the repo and run the tests:

```
npm test
```

The image output will be in test/out.
