### ISSUE TITLE
Support quadkey urls (Bing Maps)

### ISSUE THREAD

**Issue by BKSnake** [StephanGeorg/staticmaps#65]
Hello 

Could you help me to understand? Ho can I use this lib with Bing Maps. I need generate some image and i have Key to Bing Maps

Thanks

**Comment by StephanGeorg** [comment]
staticmaps@1.9.1 now supports `{quadkeys}` and Bing Maps.

https://github.com/StephanGeorg/staticmaps/blob/06a73a6401efb079ff2d2ca4c8e0225b48cf7a4c/test/staticmaps.js#L38-L46
