### ISSUE TITLE
Sharp vulnerability

### ISSUE THREAD

**Issue by Mathieu-DA** [StephanGeorg/staticmaps#72]
staticmaps currently depends on a vulnerable version of sharp (2.30.1)
Is it possible to upgrade to 2.30.5 ?
See this **[sharp issue](https://github.com/lovell/sharp/issues/3237)**.
Thanks

**Comment by StephanGeorg** [comment]
Sure, please do a Pull Request and I will merge it right away.

**Comment by Mathieu-DA** [comment]
@StephanGeorg can you accept the PR please?

**Comment by StephanGeorg** [comment]
Fixed with 2ee1588786aacc2e8114af4fd068583265134afc

**Comment by StephanGeorg** [comment]
Thanks for noticing @Mathieu-DA and sry for the delay.
