### ISSUE TITLE
Pull request still not accepted - Libary / Project dead?

### ISSUE THREAD

**Issue by Semurak** [StephanGeorg/staticmaps#78]
Hello, its almost a year now and pull request #68 is still not merged, I even asked and no response 😪 It's such a cool and helpful libary, but this is just sad! Big Thanks for the work!

I'm using the fork of @JorgenPhi for almost 6 months now and his added feature works like a charm, but I need a higher sharp version for better cross-platform support (docker) to be more accessible (this repo somehow updated to the correct version .. but no accepted PR). 

I'm using this libary for a community project, which helps emergency services to safe lives on a daily basis. Adding layer support helps them to find important POIs on a printed map.

Do I really have to fork this libary again and merge it by myself?

I hope that the pull request gets accepted 🙏

**Comment by StephanGeorg** [comment]
Sorry for all the delays. Merged and published to npm staticmaps@1.11.0.

**Comment by StephanGeorg** [comment]
Thanks again for the PR @JorgenPhi and finally merged and published.
