### ISSUE TITLE
Map is bigger than BBOX

### ISSUE THREAD

**Issue by samuel-litzler** [StephanGeorg/staticmaps#84]
My map (512x512) is bigger than the bbox i have passed ( `[4.8514292,  45.7795070, 4.8535790, 45.7779198]` )

I set paddingX / Y to 0 and i see that nothing change.

No padding : 
![image](https://user-images.githubusercontent.com/24872653/224281737-514a411f-34cc-45bd-963a-4f667c3367fd.png)

Padding : 1
![image](https://user-images.githubusercontent.com/24872653/224281658-1b70aac5-6126-40d0-adb5-29b81a85a62d.png)

![image](https://user-images.githubusercontent.com/24872653/224284236-72b1f3af-b07a-4859-b343-5319bc52f2e5.png)
 I draw my bbox with addPolygon and there is... no padding option is set.

**Comment by samuel-litzler** [comment]
result on geojson.io with points, bbox and test polygon 
![image](https://user-images.githubusercontent.com/24872653/224284500-fce659a2-a2f8-4edc-8ee1-4c9cdfc7d9bd.png)

**Comment by samuel-litzler** [comment]
I read in the doc : "If specifying a bounding box instead of a center, the optimal zoom will be calculated."

If i use BBOX its because i need precision with zoom level. But if the zoom will be calculated again, so the bbox is useless :/

**Comment by samuel-litzler** [comment]
I try with zoom / lat / lng and i understand with there is padding with bbox.

Zoom cant go bigger that 17, after 17, it's always the same zoom (here zoom 23) 
![image](https://user-images.githubusercontent.com/24872653/224291511-caf72d54-bd1d-4148-8ad4-f22d4e47f117.png)

**Comment by samuel-litzler** [comment]
Oups i just see in the doc : 
![image](https://user-images.githubusercontent.com/24872653/224291960-7e604f35-f223-4ef2-a44c-412ee632f2b0.png)
![image](https://user-images.githubusercontent.com/24872653/224291969-78dda25c-a948-47fc-80ce-5dcb45e40f80.png)

I think this not a good use to set maxZoom by default if we use bbox to generate the map.

**Comment by gerhardsletten** [comment]
The reason crop of map is not 100% the same as features or bbox, is that zoom is limited to whole numbers used when zoom is replaced with the `{z}` in the tileUrl: [source](https://github.com/StephanGeorg/staticmaps/blob/master/src/staticmaps.js#L276)

```js
// tileUrl: https://tile.openstreetmap.org/{z}/{x}/{y}.png
config.tileUrl.replace('{z}', this.zoom).replace('{x}', tileX).replace('{y}', tileY);
```

To be able to do a 100% correct crop of the map, you would need to change the algorithm and upscale the render and later crop the image. Not sure if this is a task for this repo, or its better suited in a your own code.

If `map.render()` could return the exact bbox / scale the map is rendered in  this should be possible.
