### ISSUE TITLE
Can we change label to english?

### ISSUE THREAD

**Issue by alpeshsavalia** [StephanGeorg/staticmaps#93]
Is there any way to change chinese language text to english language?
![image](https://github.com/StephanGeorg/staticmaps/assets/19701155/1e4647b0-c093-45f3-865c-8de20698050d)

**Comment by StephanGeorg** [comment]
Yes, you can use a different base map.

**Comment by alpeshsavalia** [comment]
how can change? can you give me base map url?

**Comment by StephanGeorg** [comment]
https://github.com/StephanGeorg/staticmaps/issues/7#issuecomment-379255181
